FROM golang:1.17.0-bullseye

ENV GOPATH /go
ENV PATH "/go/bin:${PATH}"

RUN go get -u github.com/golang/dep/...

RUN mkdir -p /go/src/github.com/kinvolk/kube-spawn

WORKDIR /go/src/github.com/kinvolk/kube-spawn

ENTRYPOINT ["make", "DOCKERIZED=n"]
